### ISSUE TITLE
roon url change?

### ISSUE THREAD

**Issue by sonofwatt** [comassky/roon-docker-server#3]
I'm getting an error when I try to start a new roon-docker-server container. 

> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   178  100   178    0     0    725      0 --:--:-- --:--:-- --:--:--   726
> bzip2: (stdin) is not a bzip2 file.
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> /install.sh: line 8: /app/RoonServer/start.sh: No such file or directory

The closest thing I could find to this issue is https://community.roonlabs.com/t/roonbridge-fails-to-update-with-bzip2-stdin-is-not-a-bzip2-file-error/196153

Is it possible I'm running into the same issue?
I wonder if it's possible to add something like "ROON_SERVER_URL" to the yaml?

**Comment by comassky** [comment]
I think it's fixed wit -L option, just pull and retry.

Roon add a redirection so curl command was KO

**Comment by comassky** [comment]
@sonofwatt Fixed imho

FYI you can set ROON_SERVER_URL env var inside docker-compose or docker run command

ROON_SERVER_URL=http://download.roonlabs.com/builds/RoonServer_linuxx64.tar.bz2

**Comment by comassky** [comment]
Fixed and push on Docker hub

**Comment by comassky** [comment]
Fixed and push on Docker hub
